area-Assimp:
- any: ['src/Assimp/**/*']

area-BuildTools:
- any: ['src/Core/Silk.NET.BuildTools/**/*']

area-Input:
- any: ['src/Input/**/*']

area-Windowing:
- any: ['src/Windowing/**/*']

area-OpenAL:
- any: ['src/OpenAL/**/*']

area-OpenCL:
- any: ['src/OpenCL/**/*']

area-OpenXR:
- any: ['src/OpenXR/**/*']

area-Vulkan:
- any: ['src/Vulkan/**/*']

area-DirectX/Windows:
- any: ['src/Microsoft/**/*']

area-FEMFX:
- any: ['src/AMD/FEMFX/**/*']
